// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'model/category_dm.dart';
import 'model/event_dm.dart';
import 'model/user_dm.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC78jtrD81DIl0OnEqrr-XhIHBbRDJ0U6Q',
    appId: '1:646920831007:web:3c0c0b66090c4b3e7d152a',
    messagingSenderId: '646920831007',
    projectId: 'event-8fc32',
    authDomain: 'event-8fc32.firebaseapp.com',
    storageBucket: 'event-8fc32.firebasestorage.app',
    measurementId: 'G-4K9463LM1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYLgkULGFp7AMjJxiCoSvZeHy1gkxoNug',
    appId: '1:646920831007:android:3147531126a722c57d152a',
    messagingSenderId: '646920831007',
    projectId: 'event-8fc32',
    storageBucket: 'event-8fc32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMiombnMvEcAePWTU6EPxFswMKAAjQLkM',
    appId: '1:646920831007:ios:148a9303167f0fa07d152a',
    messagingSenderId: '646920831007',
    projectId: 'event-8fc32',
    storageBucket: 'event-8fc32.firebasestorage.app',
    iosBundleId: 'com.example.eventlyC13Online',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMiombnMvEcAePWTU6EPxFswMKAAjQLkM',
    appId: '1:646920831007:ios:148a9303167f0fa07d152a',
    messagingSenderId: '646920831007',
    projectId: 'event-8fc32',
    storageBucket: 'event-8fc32.firebasestorage.app',
    iosBundleId: 'com.example.eventlyC13Online',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC78jtrD81DIl0OnEqrr-XhIHBbRDJ0U6Q',
    appId: '1:646920831007:web:afc952e0dc6bb7ea7d152a',
    messagingSenderId: '646920831007',
    projectId: 'event-8fc32',
    authDomain: 'event-8fc32.firebaseapp.com',
    storageBucket: 'event-8fc32.firebasestorage.app',
    measurementId: 'G-QPQPF6TE0W',
  );
}
///Event Features
Future<List<EventDM>> getEventsByCategory(String category) async {
  if (category == CategoryDM.allCategory.name) {
    var eventsCollection = FirebaseFirestore.instance.collection("events");
    QuerySnapshot collectionSnapshot = await eventsCollection.get();
    List<QueryDocumentSnapshot> documents = collectionSnapshot.docs;
    List<EventDM> events = documents.map(documentSnapshotToEventDM).toList();
    return events;
  } else {
    var eventsCollection = FirebaseFirestore.instance.collection("events");
    QuerySnapshot collectionSnapshot =
    await eventsCollection.where("category", isEqualTo: category).get();
    List<QueryDocumentSnapshot> documents = collectionSnapshot.docs;
    List<EventDM> events = documents.map(documentSnapshotToEventDM).toList();
    return events;
  }
}

EventDM documentSnapshotToEventDM(QueryDocumentSnapshot doc) {
  Map<String, dynamic> json = doc.data() as Map<String, dynamic>;
  return EventDM.fromJson(json);
}

Future<void> addEvent(EventDM event) {
  var eventsCollection = FirebaseFirestore.instance.collection("events");
  return eventsCollection.add(event.toJson());
}
//
///Assignment // Future<void> updateEvent(EventDM newEvent){}
//
// ///User Features
// Future<void> addEventToFavorites(String eventId){}
//
// Future<void> removeEventFromFavorites(String eventId){}

Future<void> createUserInFirestore(UserDM userDm) {
  // UserDM(id: "1", name: "ahmed", email: "ahmed@gmail.com", favoritesEventsIds: ["1"])???
  // {"id": "1", "name": "ahmed", "email": "ahmed@gmail.com", "favoritesEventsIds": ["1"]}
  var usersCollection = FirebaseFirestore.instance.collection("users");
  DocumentReference newUserDoc = usersCollection.doc(userDm.id);
  return newUserDoc.set(userDm.toJson());

  ///Create an empty document with existing id
  /// usersCollection.add(userDm.toJson()); ///Creates a document with an auto generated id

  ///Add doc
  // usersCollection.add(Json);
  // usersCollection.get() ->>Json
}

Future<UserDM> getUserFromFirestore(String id) async {
  CollectionReference usersCollection =
  FirebaseFirestore.instance.collection("users");

  ///Create collection if it does not exist
  ///Or Gets the collection if it exists

  DocumentReference userDoc = usersCollection.doc(id);

  ///Create empty document if id does not exits and it gets the documents if it exists
  DocumentSnapshot userSnapshot = await userDoc.get();
  Map<Object, Object?> json = userSnapshot.data() as Map<Object, Object?>;
  return UserDM.fromJson(json);
  // return UserDM(id: json["id"], name: json["name"],
  //     email: json["email"], favoritesEventsIds: json["favoritesEventsIds"]);
}

///JSON ??? Java script object notation
